<?php

Model::addSqlQuery('QUESTIONNAIRE_LIST',
	'SELECT * FROM QUESTIONNAIRE ORDER BY TITRE');

Model::addSqlQuery('QUESTIONNAIRE_CREATE',
	'INSERT INTO `question` (`ID_QUESTIONNAIRE`, `ID_CONSIGNE`, `TITRE`, `DESCTIPTION_QUESTIONNAIRE`, `DATE_OUVERTURE`, `DATE_FERMETURE`, `ETAT`) VALUES (NULL, :id_c, :titre, :des_qu, :d_o, :d_f, :etat)');

Model::addSqlQuery('GET_QUESTIONNAIRE_BY_ID',
	'SELECT * FROM QUESTIONNAIRE WHERE ID_QUESTIONNAIRE = :id_q');

Model::addSqlQuery('GET_QUESTIONNAIRES_BY_IDUSER',
	'SELECT Q.* FROM QUESTIONNAIRE Q JOIN CREER C ON Q.ID_QUESTIONNAIRE=C.ID_QUESTIONNAIRE WHERE C.ID_USER=:id_user');

	?>
