<?php

Model::addSqlQuery('QUESTION_LIST',
	'SELECT * FROM QUESTION ORDER BY TAG');

Model::addSqlQuery('QUESTION_CREATE',
	'INSERT INTO `question` (`ID_QUESTION`, `ID_CONSIGNE`, `TAG`, `TYPE_QUESTION`, `NB_REPONSES`, `DESCRIPTION_QUESTION`) VALUES (NULL, :id_c, :tag, :type, :nb_r, :des_ques)');

Model::addSqlQuery('GET_QUESTION_BY_ID',
	'SELECT * FROM QUESTION WHERE ID_QUESTION = :id_q');

Model::addSqlQuery('GET_QUESTIONS_BY_QUESTIONNAIRE',
	'SELECT Q.* FROM QUESTION Q JOIN EST_COMPOSE EC ON Q.ID_QUESTION=EC.ID_QUESTION WHERE ID_QUESTIONNAIRE = :id_q');

	?>
